{% set name = "leb128" %}
{% set version = "1.0.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mohanson/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ec495a1ad9e14656f4b6c59b2baae1b96001d7e25d6a8a47edba17799a062c65

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - test
  imports:
    - leb128
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test

about:
  home: https://github.com/mohanson/leb128
  summary: LEB128(Little Endian Base 128)
  description: |
    LEB128 or Little Endian Base 128 is a form of variable-length code
    compression used to store an arbitrarily large integer in a small number
    of bytes. LEB128 is used in the DWARF debug file format and the
    WebAssembly binary encoding for all integer literals.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/mohanson/leb128
  doc_url: https://github.com/mohanson/leb128#readme

extra:
  recipe-maintainers:
    - bollwyvl
