{% set version = "1.0.5" %}

package:
  name: leb128
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/leb128/leb128-{{ version }}.tar.gz
  sha256: cb16001f0087b499ab51f6b8e3ef8377ba14a0c9990db85316dedf0ad4a54e80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - leb128
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mohanson/leb128
  summary: LEB128(Little Endian Base 128)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
